### ISSUE TITLE
ugh bug :(

### ISSUE THREAD

**Issue by Parnell85** [mythridium/combat-simulator#62] opened 2024-11-13 19:50 UTC
**Describe the bug**
It wont let me change gear to sim

**To Reproduce**
I click the # gear Im using and this pops up

**Expected behavior**
to load the gear

**Device:**
Browser

[Ugh Bug.txt](https://github.com/user-attachments/files/17738491/Ugh.Bug.txt)

**Comment by mythridium** [comment] 2024-11-13 20:33
Thanks for taking the time to report this issue, this was caused by mods that added new realms but didn't register with combat sim, I needed to filter these out when importing as the sim doesn't know about their existence.

This has been released in v3.1.18

Fixed in [213b60d](https://github.com/mythridium/combat-simulator/commit/213b60d86c15d2a16acb70352f28d51646b3455c)

**Closed by mythridium** 2024-11-13 20:33 UTC
Labels: bug
