### ISSUE TITLE
Issue loading the mod

### ISSUE THREAD

**Issue by EmilVorre** [mythridium/combat-simulator#10] opened 2023-09-14 21:26 UTC
**Describe the bug**

**To Reproduce**
1. click the mod in the side menu

**Expected behavior**
does not load

**Screenshots**
![image](https://github.com/mythridium/combat-simulator/assets/117618821/3a569372-4eb6-485b-8692-303e8399bc31)

**Device:**
Google chrome and Apple Iphone IOS

**Save**
Attach your save file using one of the following:
(https://melvoridle.com/save/xEAO9lHt)

**Mod List**
Mod Manager > My Mods > Copy Mod List
SEMI Core
SEMI Auto Farming
Show Skill Modifiers
SEMI Auto Master
SEMI Auto Runecrafting
SEMI Auto Run
Bank Space Manager
Semi Auto Township
SEMI Auto Eat
SEMI Auto Collect Stockpiles
Bank Tab Values
SEMI Drop Chances
ETA
Mastery Pool Can Overflow
SEMI Auto Loot
Item Uses
Shop Item Owned Indicator
Bypass Agility Costs
Speedup
AutoSort
SEMI Auto Smith Bars
Show Dungeon Completion Count
Upgrade All Potions
SEMI Auto Open
Better Offline Recap
SEMI Auto Slayer
Show Slayer Task Attack Style
Repeat Current Slayer Task
[Myth] Combat Simulator

**Comment by mythridium** [comment] 2023-09-14 21:58
Thank you so much for providing additional details. Unfortunately I'm not able to reproduce this on my end with your save, so we'll need to dig into the error a little bit more since the error that it's showing you isn't enough to tell me whats happening.

Do you mind performing the following steps for me.
1. Open up the game in chrome browser
2. Press the F12 key to open up the developer tools
3. Click on the Console tab at the top of the page
![image](https://github.com/mythridium/combat-simulator/assets/132613374/f57b89c1-02cf-4b4a-888d-6f933a715fe3)
4. Load into your save file and attach a picture of everything you see, most importantly anything listed in red

Hopefully we can squash this bug for you!

**Comment by EmilVorre** [comment] 2023-09-14 22:00
i get this message 
![image](https://github.com/mythridium/combat-simulator/assets/117618821/32b49223-462d-40a8-ac33-ccf25608b353)

**Comment by mythridium** [comment] 2023-09-14 22:03
Hmm, that is very interesting.

Do you mind clicking on the little chevron on the left to expand it and send a picture of that. Then click the file name and it should take you to the file that the error is originating from. Send a picture of that too.

![image](https://github.com/mythridium/combat-simulator/assets/132613374/698c1133-2e2a-4bd8-9bfd-3d3e717cd10d)

**Comment by EmilVorre** [comment] 2023-09-14 22:05
here a picture of that 
![image](https://github.com/mythridium/combat-simulator/assets/117618821/aedcc3bc-581d-40f9-91f3-67ae23821996)
![image](https://github.com/mythridium/combat-simulator/assets/117618821/484f78ab-88e6-45ed-8839-d926396692bd)
![image](https://github.com/mythridium/combat-simulator/assets/117618821/cd3d19e2-d341-4975-867a-f5acb67b26a5)

**Comment by mythridium** [comment] 2023-09-14 22:07
And what is the url in the browser that you are loading the game from?

![image](https://github.com/mythridium/combat-simulator/assets/132613374/87f8758a-980b-497c-af97-9352b5200ae6)

**Comment by EmilVorre** [comment] 2023-09-14 22:08
![image](https://github.com/mythridium/combat-simulator/assets/117618821/49bf562c-ea88-448e-bb14-88e2b558775f)

**Comment by EmilVorre** [comment] 2023-09-14 22:08
works then i delete the # at the end of the url

**Comment by EmilVorre** [comment] 2023-09-14 22:09
thank you for the help with the problem :) have a great day

**Comment by mythridium** [comment] 2023-09-14 22:09
Thanks so much, I'll see if I can clean this up a little, so it isn't so easily broken.

**Comment by mythridium** [comment] 2023-09-15 00:43
Thanks again for your help, this issue should be fixed now.

Fixed in 79935df40bebc04e459d4f0fd2bedfef7c11f3d2

**Closed by mythridium** 2023-09-15 00:43 UTC
Labels: bug
