### ISSUE TITLE
game said to copy this and report it on the issue thing

### ISSUE THREAD

**Issue by Champulin** [mythridium/combat-simulator#36] opened 2024-06-12 06:30 UTC
game.combatAreaDisplayOrder is not iterableTypeError: game.combatAreaDisplayOrder is not iterableat CombatResolver.recalculateSurvivability (blob:https://epicgames.melvoridle.com/f2cb38c0-441a-4d74-bd57-617c12cb300e:2461:32)at PotionManager.<anonymous> (blob:https://epicgames.melvoridle.com/f2cb38c0-441a-4d74-bd57-617c12cb300e:3240:24)at typeName.<computed> (https://epicgames.melvoridle.com/assets/js/built/mod.js?11265:599:52)at SimPlayer.setPotion (blob:https://epicgames.melvoridle.com/bf8d3af8-459a-4d90-8208-551f70212daa:1:133498)at SimGame.resetToBlankState (blob:https://epicgames.melvoridle.com/bf8d3af8-459a-4d90-8208-551f70212daa:1:103546)at blob:https://epicgames.melvoridle.com/bf8d3af8-459a-4d90-8208-551f70212daa:1:654776at async Global.time (blob:https://epicgames.melvoridle.com/bf8d3af8-459a-4d90-8208-551f70212daa:1:93484)at async main_Main.load (blob:https://epicgames.melvoridle.com/bf8d3af8-459a-4d90-8208-551f70212daa:1:654357)at async blob:https://epicgames.melvoridle.com/bf8d3af8-459a-4d90-8208-551f70212daa:1:653609Melvor Version: v1.3Sim Version: 3.0.51Mod List:- SEMI Core- [Myth] Combat Simulator- Skill Boosts- SEMI Auto Master- SEMI Drop Chances- Show Item Sources And Uses- Kills in Combat- Upgrade All Potions- Show Dungeon Completion Count- Show Slayer Tier- Dungeon Pet Indicator- Will I Die?Save Game String:

**Comment by mythridium** [comment] 2024-06-12 06:32
Hello, thank you for reporting this issue.

This is caused by the `will i die` mod which has not been updated to v1.3 of the game and causes combat sim to throw an error as a result.

Please review your mods and disable any that have not been updated as they will cause issues.

**Comment by mythridium** [comment] 2024-06-13 00:07
Closing this, feel free to open a new issue if you find another issue. Thanks!

**Closed by mythridium** 2024-06-13 00:07 UTC
Labels: bug
