### ISSUE TITLE
Global.simulator is undefined

### ISSUE THREAD

**Issue by Botanner007** [mythridium/combat-simulator#59] opened 2024-09-04 14:59 UTC
**Device:**
Firefox

**Additional context**
When i load in i get a pop up error for the combat sim. If i try to simulate i get the error "No valid simulation data: Global.simulator is undefined. 

---

init@blob:https://melvoridle.com/de56fc56-a787-4448-9def-d5485a6466bf:1:109647
init/</duration<@blob:https://melvoridle.com/de56fc56-a787-4448-9def-d5485a6466bf:1:113091
time@blob:https://melvoridle.com/de56fc56-a787-4448-9def-d5485a6466bf:1:2691
init/<@blob:https://melvoridle.com/de56fc56-a787-4448-9def-d5485a6466bf:1:113039
onMessage@blob:https://melvoridle.com/de56fc56-a787-4448-9def-d5485a6466bf:1:94840
listen/this.self.onmessage@blob:https://melvoridle.com/de56fc56-a787-4448-9def-d5485a6466bf:1:94228

Melvor Version: v1.3?11765
Sim Version: 3.0.99

Expansions Enabled: TotH

Mod List:
 - [Myth] Combat Simulator
 - SEMI Core
 - Show Skill Modifiers
 - Item Uses
 - Reveal Unlocks
 - ETA
 - Shop Item Owned Indicator
 - SEMI Drop Chances
 - AutoSort
 - SEMI Auto Farming
 - Show Item Sources And Uses

[error.txt](https://github.com/user-attachments/files/16872803/error.txt)

**Comment by mythridium** [comment] 2024-09-14 03:46
@Botanner007 is this still an issue?

This is typically caused by a script failing to load in your browser, this could be for various reasons, such as an adblocker, vpn or network issue. This is not a wide spread issue and not something I can reproduce, so it's most likely something local to you.

I've release v3.1.0 which improves the logging in this area, if this is still an issue feel free run the game again with the new version of combat sim and post the new error you get, hopefully this sheds some more light on which exact request is failing for you.

**Comment by Botanner007** [comment] 2024-09-14 20:41
Hello, yes unfortunately i am still having an issue. I disabled ublock for Melvor and still have the issue. Here is the new error. 
[scripts faile.txt](https://github.com/user-attachments/files/17003751/scripts.faile.txt)

**Comment by mythridium** [comment] 2024-09-15 16:49
Thanks for the information, this been fixed in v3.1.1, feel free to comment if the issue persists or open a new issue.

Fixed in [6406773](https://github.com/mythridium/combat-simulator/commit/6406773042f2393585d52c3a57bf3610e5c5c564)

**Closed by mythridium** 2024-09-15 16:49 UTC
Labels: bug
