### ISSUE TITLE
Save slots not saving between sessions

### ISSUE THREAD

**Issue by Cayke0** [mythridium/combat-simulator#31] opened 2024-05-27 15:06 UTC
After modifying and overwriting a save slot, all changes are reverted after switching characters or closing the game.

**Steps to Reproduce:**
1. Load a save slot
2. Modify any parameters of that save slot (gear, skill levels, agility obstacles, etc.)
3. Overwrite the save slot with the modified parameters
4. Close the game or return to character selection
5. Reload the character
6. Back in the Combat Simulator interface, load the modified save slot

**Actual Behavior:**
The changes made to the save slot are not present; the save slot is as it was before overwriting.

**Expected Behavior:**
The changes made previously are present.

**Device:**
Browser (Opera GX)

**Additional Context:**
I am using the Combat Simulator mod on a dummy character with no progression in order to avoid using any mods on my main character. All parameters are manually entered to reflect my main character. The save slots are in a state saved a few weeks ago—the save slots used to overwrite without issue, but lately I've had to manually re-edit all my gear, stats, pets, etc. every time I want to use the mod.

**Save:**
Note again that this is a dummy save file with no progression whatsoever:
[melvoridlesave_Dummy_5-27-2024_104811AM.txt](https://github.com/mythridium/combat-simulator/files/15457348/melvoridlesave_Dummy_5-27-2024_104811AM.txt)

**Mod List:**
[Myth] Combat Simulator

**Comment by mythridium** [comment] 2024-05-27 21:04
Hello, thanks for reporting this issue. Unfortunately, I'm unable to reproduce the issue and it works as expected. I'm using chrome browser.

Do you mind opening developer tools of your browser, typically opened by pressing F12, and try overwriting the save slot. Can you send through all the content you see in the console?

Otherwise, save slots are stored in local storage, can you check that you have allowed the website to store things in local storage? Maybe this permission changed in the last few weeks?

You can also find me on discord under the same name if that it's easier to chat on, feel free to direct message me, otherwise through here is fine.

**Comment by Cayke0** [comment] 2024-05-27 21:20
Hi @mythridium, thanks for responding! I sent you a friend request on Discord, but for now I'll share this here:

Your suggestion to open dev tools was fruitful, as there seems to be an exception thrown when trying to overwrite a save slot (see attached screenshot). I tried searching through Opera GX's settings for a setting/permission related to saving to local storage, but I wasn't able to find anything.

![image](https://github.com/mythridium/combat-simulator/assets/124019352/e7ad9346-cb07-4c0e-9e83-fef37a640d6b)

**Comment by mythridium** [comment] 2024-05-27 22:28
Confirmed as resolved on discord after moving from localstorage to indexeddb.

Fixed in f6aef0d99b02d5a7fd75df2e97f9baeecec16236

**Closed by mythridium** 2024-05-27 22:28 UTC
Labels: bug
